---
  - name: Remove temporary files
    file: path={{ item }} state=absent
    with_items:
     - /root/repluser.ldif
     - /root/ldap.inf
     - /root/suplier_changelog.ldif
     - /root/suplier_replica.ldif
