---
   - name: Copy installation templates
     template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
     with_items:
      - supplier_changelog.ldif
      - supplier_replica.ldif
      - supplier_replication_agreement.ldif
      - supplier_init_consumer.ldif

   - name: Configuring replication supplier changelog
     shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_changelog.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))

   - name: Configuring replication supplier replica
     shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_replica.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1)or(results.stderr.find('replica already configured for') != -1))

   - name: Configuring replication agreement
     shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_replication_agreement.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))

   - name: Initializing consumer from supplier
     shell: ldapmodify -D {{ rootdn }} -w {{ password }} -h localhost -v < /root/supplier_init_consumer.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))
     when: init_consumer

