---
   - name: Copy installation templates
     template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
     with_items:
      - suplier_changelog.ldif
      - suplier_replica.ldif

   - name: adding changelog entry
     shell: ldapmodify -D {{ ldap_rootdn }} -w {{ ldap_password }} -h localhost -v < /root/suplier_changelog.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))

   - name: Configuring suplier replica
     shell: ldapmodify -D {{ ldap_rootdn }} -w {{ ldap_password }} -h localhost -v < /root/suplier_replica.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))
