---
   - name: Copy installation templates
     template: src=templates/{{ item }}.j2 dest=/root/{{ item }}
     with_items:
      - supplier_changelog.ldif
      - supplier_replica.ldif
      - supplier_replication_agreement.ldif
     when: enable_replication_supplier

   - name: Configuring replication supplier changelog
     shell: ldapmodify -D {{ ldap_rootdn }} -w {{ ldap_password }} -h localhost -v < /root/supplier_changelog.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))
     when: enable_replication_supplier

   - name: Configuring replication suplier replica
     shell: ldapmodify -D {{ ldap_rootdn }} -w {{ ldap_password }} -h localhost -v < /root/supplier_replica.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1)or(results.stderr.find('replica already configured for') != -1))
     when: enable_replication_supplier

   - name: Configuring replication agreement
     shell: ldapmodify -D {{ ldap_rootdn }} -w {{ ldap_password }} -h localhost -v < /root/supplier_replication_agreement.ldif
     register: results
     failed_when:  not((results.rc == 0)or(results.stderr.find('Already exists') != -1))
     when: enable_replication_supplier

